schemaVersion: 2.2.0
metadata:
  name: coolstore-microservice-devx
attributes:
  che-theia.eclipse.org/sidecar-policy: mergeImage
components:
  - name: universal-developer-image
    container: 
      image: registry.redhat.io/devspaces/udi-rhel8:3.12
      memoryLimit: 6Gi
      mountSources: true
commands: []